import marimo

__generated_with = "0.23.5"
app = marimo.App(width="medium")


@app.cell
def _():
    from collections import Counter
    from pathlib import Path
    from ast import literal_eval
    import marimo as mo
    import pandas as pd
    import numpy as np
    import plotly.express as px
    import plotly.graph_objects as go

    return Counter, Path, go, literal_eval, mo, np, pd, px


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Rumen Metagenome Datasets on SRA

    Datasets' metadata was downloaded using `dataFinder` script. Data was obtained on 04Apr2026.
    """)
    return


@app.cell
def _(Path, literal_eval, np, pd):
    sra_data_path = Path("../data/combined_sra_ena_metadata__2026_05_09.tsv")

    r_data = pd.read_csv(
        sra_data_path,
        sep="\t",
        converters={
            "Published": pd.to_datetime,
            "Bases": lambda x: int(float(x)) if x == x and x != "" else np.nan,
            # "collection_date__ENA": pd.to_datetime,
            # "collection_date_end__ENA": pd.to_datetime,
            # "collection_date_start__ENA": pd.to_datetime,
            # "collection_date_start__ENA": pd.to_datetime,
            # "first_created__ENA": pd.to_datetime,
            "first_public__ENA": pd.to_datetime,
            "SampleAttributes": lambda x: (
                literal_eval(x) if x == x and x != "" else {}
            ),
        },
        dtype={
            "SizeGB": float,
        },
        low_memory=False,
        na_values=["unspecified", ""],
    )
    return (r_data,)


@app.cell
def _(r_data):
    r_data
    return


@app.cell
def _(r_data):
    print(f"Number of studies: {len((studies:=r_data['SRAStudy'].unique()))}")
    print(
        f"Library Strategies covered: {list(r_data['LibraryStrategy'].unique())}"
    )
    print(f"Library sources covered: {list(r_data['LibrarySource'].unique())}")
    print(f"Sequencers used: {list(r_data['Sequencer'].unique())}")
    return


@app.cell
def _(r_data):
    # sort the tech type for the samples

    # generated by GPT-4o based on the sequencers column
    read_length_mapping = {
        # Short-read sequencing technologies
        "454 GS FLX": "short-read",
        "Illumina Genome Analyzer": "short-read",
        "Illumina Genome Analyzer II": "short-read",
        "Illumina HiSeq 2000": "short-read",
        "454 GS FLX Titanium": "short-read",
        "unspecified": "short-read",  # Default assumption
        "454 GS Junior": "short-read",
        "454 GS FLX+": "short-read",
        "Illumina MiSeq": "short-read",
        "Ion Torrent PGM": "short-read",
        "Illumina HiScanSQ": "short-read",
        "Illumina HiSeq 2500": "short-read",
        "454 GS": "short-read",
        "NextSeq 500": "short-read",
        "Illumina Genome Analyzer IIx": "short-read",
        "Illumina HiSeq 4000": "short-read",
        "Illumina MiniSeq": "short-read",
        "HiSeq X Ten": "short-read",
        "Illumina HiSeq 3000": "short-read",
        "Ion S5 XL": "short-read",
        "Illumina NovaSeq 6000": "short-read",
        "Illumina HiSeq X Ten": "short-read",
        "Ion Torrent S5 XL": "short-read",
        "Illumina HiSeq 1000": "short-read",
        "Illumina HiSeq 1500": "short-read",
        "Illumina HiSeq X": "short-read",
        "MGISEQ-2000RS": "short-read",
        "AB 5500 Genetic Analyzer": "short-read",
        "BGISEQ-500": "short-read",
        "Illumina NovaSeq X": "short-read",
        "NextSeq 2000": "short-read",
        "Illumina NovaSeq X Plus": "short-read",
        "DNBSEQ-T7": "short-read",
        "DNBSEQ-G50": "short-read",
        "DNBSEQ-G400": "short-read",
        "AB 5500xl Genetic Analyzer": "short-read",
        "MiSeq i100": "short-read",
        "Illumina MiSeq": "short-read",
        "Illumina Miseq": "short-read",
        "pyrosequencing": "short-read",
        "PGM Ion-Torrent": "short-read",
        "454 Pyrosequencing": "short-read",
        "Ion Torrent": "short-read",
        "LS454": "short-read",
        # Long-read sequencing technologies
        "Sequel": "long-read",
        "PacBio RS II": "long-read",
        "MinION": "long-read",
        "PromethION": "long-read",
        "Sequel II": "long-read",
        "GridION": "long-read",
        "PacBio RS": "long-read",
        "Sequel IIe": "long-read",
    }
    r_data["sequencing_type"] = [
        read_length_mapping.get(r, "unknown") for r in r_data["Sequencer"]
    ]
    r_data["sequencing_type"] = [
        read_length_mapping.get(seq_ena, "unknown") if st == "unknown" else st
        for st, seq_ena in zip(
            r_data["sequencing_type"], r_data["instrument_model__ENA"]
        )
    ]
    r_data["sequencing_type"] = [
        read_length_mapping.get(seq_ena, "unknown") if st == "unknown" else st
        for st, seq_ena in zip(
            r_data["sequencing_type"], r_data["sequencing_method__ENA"]
        )
    ]
    r_data["sequencing_type"] = [
        read_length_mapping.get(seq_ena, "unknown") if st == "unknown" else st
        for st, seq_ena in zip(
            r_data["sequencing_type"], r_data["instrument_platform__ENA"]
        )
    ]
    return


@app.cell
def _(r_data):
    r_data["sequencing_type"].value_counts()
    return


@app.cell
def _(r_data):
    r_data.loc[r_data["sequencing_type"] == "unknown"][
        [
            "Sequencer",
            "instrument_model__ENA",
            "sequencing_method__ENA",
            "instrument_platform__ENA",
        ]
    ]
    return


@app.cell
def _(r_data):
    # deal with the published date
    # use 'Pubished' from SRA and 'first_public__ENA' from ENA

    dates = [
        s if s == s else e
        for s, e in zip(r_data["Published"], r_data["first_public__ENA"])
    ]
    r_data["Published"] = dates

    print(
        f"Data ranges from {sorted(r_data['Published'])[0]} -TO- {sorted(r_data['Published'])[-1]}"
    )
    return


@app.cell
def _(r_data):
    # deal with the library strategy
    # for SRA data that is 'LibraryStrategy' and for ENA data that is 'library_strategy__ENA'
    libstrat = [
        s_lib if s_lib == s_lib else e_lib
        for s_lib, e_lib in zip(
            r_data["LibraryStrategy"], r_data["library_strategy__ENA"]
        )
    ]
    r_data["LibraryStrategy"] = libstrat

    print(
        f"Number of missing values for LibraryStrategy: {sum(r_data['LibraryStrategy'].isna())}"
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    Questions:
    - What are OTHER and WCS library strategies?
    - How many WGS/shotgun datasets are there?
    """)
    return


@app.cell
def _(r_data):
    # whole chromosome sequencing - not sure what that means for metagenomic... >> exclude these samples
    r_data.loc[r_data["LibraryStrategy"] == "WCS"]
    return


@app.cell
def _(r_data):
    # these look like WGS as they have high Gb data range >> include theses but remove the 16S and QPCR samples from the OTHER dataset
    r_data.loc[r_data["LibraryStrategy"] == "OTHER"]
    return


@app.cell
def _(r_data):
    # deal with the Gb data
    # for SRA data this is 'Bases' and for 'base_count__ENA'
    gb_bases = [
        s_bases / 1e9 if s_bases == s_bases else e_bases / 1e9
        for s_bases, e_bases in zip(r_data["Bases"], r_data["base_count__ENA"])
    ]
    r_data["Gb"] = gb_bases
    return


@app.cell
def _(r_data):
    # one NAN dataset for Gb > not a big problem
    r_data.loc[r_data["Gb"].isna()]
    return


@app.cell
def _(Counter, r_data):
    # deal with the hosts, this is coming from multiple columns potentially
    # SRA: SampleAttributes host_scientific_name, host or breed

    host = []
    for h, ena_h, xie in zip(
        r_data["SampleAttributes"],
        r_data["host_scientific_name__ENA"],
        r_data["Animal_species__Xie_sci_2026"],
    ):
        if ena_h == ena_h:
            host.append(ena_h)
        elif h.get("host scientific name"):
            host.append(h.get("host scientific name"))
        elif h.get("host"):
            host.append(h.get("host"))
        elif xie == xie:
            host.append(xie)
        elif h.get("breed"):
            host.append(h.get("breed"))
        else:
            host.append("missing")
    r_data["host"] = host
    Counter(host)
    return


@app.cell(hide_code=True)
def _():
    # generated by GPT-4o based on the host columns
    animal_mapping = {
        "cattle_16": "Cattle",
        "Ovis_aries": "Sheep",
        "Camel-28": "Camel",
        "Sheep-5": "Sheep",
        "Sheep-17": "Sheep",
        "024": "Missing",
        "Rangifer tarandus 2S_YN_A": "Deer",
        "Hu lamb": "Sheep",
        "buffalo": "Buffalo",
        "Goat-30": "Goat",
        "Ovies": "Sheep",
        "sikadeer": "Deer",
        "Boer goats rumen": "Goat",
        "Goat-28": "Goat",
        "rumencowB_replicate2": "Cattle",
        "HF150992": "Missing",
        "goat 1": "Goat",
        "Mus musculus": "Mouse",
        "Holstein cow": "Cattle",
        "bovine1 in CAR": "Cattle",
        "cattle_19": "Cattle",
        "Ovis aries L.": "Sheep",
        "Giraffa camelopardalis giraffa": "Giraffe",
        "goat 5": "Goat",
        "Hanwoo": "Cattle",
        "Extraction_control_2": "Control",
        "Ovies aris": "Sheep",
        "Small-tail Han sheep": "Sheep",
        "sheep-7": "Sheep",
        "Holstein Fresian": "Cattle",
        "Sheep-16": "Sheep",
        "Zymo Mock #D6311": "Control",
        "goatT302": "Goat",
        "Oviesss": "Sheep",
        "sheep-2": "Sheep",
        "Holstein X Jersey cow": "Cattle",
        "Rangifer tarandus 11W_YN_A_F": "Deer",
        "dairy cows8": "Cattle",
        "LF150268": "Missing",
        "Goat-13": "Goat",
        "cattle_2": "Cattle",
        "Dairy cow 13": "Cattle",
        "Ovies ries": "Sheep",
        "Rangifer tarandus 6W_YN_Y": "Deer",
        "dairy cows3": "Cattle",
        "dairy cows9": "Cattle",
        "Camel-34": "Camel",
        "bovine7 in CON": "Cattle",
        "Capreolus capreolus": "Deer",
        "Goat-8": "Goat",
        "Sheep-2": "Sheep",
        "Goat-34": "Goat",
        "goat kids 7": "Goat",
        "dairy cows19": "Cattle",
        "Boer goat": "Goat",
        "Extraction_control_1": "Missing",
        "Antilocapra americana": "Antelope",
        "goat 7": "Goat",
        "Rangifer tarandus 26W_M_C": "Deer",
        "Rangifer tarandus 31W_M_A_M": "Deer",
        "0624": "Missing",
        "Giraffa camelopardalis rotschildi": "Giraffe",
        "yak": "Yak",
        "Abo-6792_R1": "Missing",
        "Goat-16": "Goat",
        "beef individual 10": "Cattle",
        "lactating Holstein dairy cow (Bos taurus)": "Cattle",
        "goat 9": "Goat",
        "Alces alces": "Moose",
        "Holstein dairy cow": "Cattle",
        "Zymo Mock #D6309": "Missing",
        "Gayal": "Cattle",
        "60149": "Missing",
        "cattle_5": "Cattle",
        "Boer Goat": "Goat",
        "bovine6 in CON": "Cattle",
        "Dairy cow 4": "Cattle",
        "Sheep-7": "Sheep",
        "dairy cows17": "Cattle",
        "Belmont Red Composite steers": "Cattle",
        "Goat-38": "Goat",
        "Bos grunniens": "Yak",
        "dairy cows24": "Cattle",
        "0202": "Missing",
        "Moschus berezovskii": "Deer",
        "Goat-19": "Goat",
        "yak5": "Yak",
        "Camel-22": "Camel",
        "HF151026": "Missing",
        "xinjiang alar city": "Missing",
        "rumencowA_replicate3": "Cattle",
        "rumen": "Missing",
        "Sheep-9": "Sheep",
        "Goat-40": "Goat",
        "bovine8 in CON": "Cattle",
        "cattle_7": "Cattle",
        "sheep-12": "Sheep",
        "sheep-11": "Sheep",
        "Rangifer tarandus 30W_M_A_M": "Deer",
        "Rangifer tarandus 1W_YN_C": "Deer",
        "Holstein Bulls": "Cattle",
        "goat": "Goat",
        "steers": "Cattle",
        "Sheep4": "Sheep",
        "0625": "Missing",
        "Hydropotes inermis": "Deer",
        "bovine4 in SCFP": "Cattle",
        "not applicabe": "Missing",
        "Sheep1": "Sheep",
        "Elaphurus davidianus": "Deer",
        "cattle_15": "Cattle",
        "Tibetan goat 6": "Goat",
        "Dairy cow 22": "Cattle",
        "goatH2": "Goat",
        "beef individual 11": "Cattle",
        "Tibetan goat 5": "Goat",
        "Dairy cow 25": "Cattle",
        "Capra hircus coreanae": "Goat",
        "goats": "Goat",
        "Qichuan Beef": "Cattle",
        "Bos taurus taurus": "Cattle",
        "Rangifer tarandus 10W_YN_A_F": "Deer",
        "Camel-27": "Camel",
        "Goat-10": "Goat",
        "Holstein-Friesian cow": "Cattle",
        "Zymo Mock #D6305": "Missing",
        "CALF": "Cattle",
        "Tibetan goat 4": "Goat",
        "Goat-20": "Goat",
        "Abo-6775_R1": "Missing",
        "Mongolian cattle": "Cattle",
        "Goat-27": "Goat",
        "roedeer": "Deer",
        "Rangifer tarandus 3S_YN_A": "Deer",
        "bovine10 in SCFP": "Cattle",
        "lactating goat": "Goat",
        "LF150387": "Missing",
        "Rangifer tarandus 21W_N_A_M": "Deer",
        "Goat-22": "Goat",
        "Rangifer tarandus": "Deer",
        "Goat-5": "Goat",
        "Abo-6773_R1": "Missing",
        "Black Bengal Goat (Capra hircus)": "Goat",
        "not applicable": "Missing",
        "Loxodonta": "Elephant",
        "bovine4 in CON": "Cattle",
        "Zymo Mock #D6306": "Missing",
        "Hu sheep": "Sheep",
        "Tibetan sheep": "Sheep",
        "Nellore": "Cattle",
        "dairy cows15": "Cattle",
        "Dairy cow 6": "Cattle",
        "goat kids 11": "Goat",
        "Taurotragus": "Eland",
        "Cervus nippon yakushimae": "Deer",
        "cashmere goat": "Goat",
        "Homo sapiens": "Human",
        "goat kids 17": "Goat",
        "Rangifer tarandus 3W_YN_C": "Deer",
        "Goat-25": "Goat",
        "cattle_11": "Cattle",
        "Camel-14": "Camel",
        "goat 2": "Goat",
        "dairy cow-4": "Cattle",
        "goat 6": "Goat",
        "Camel-21": "Camel",
        "Dairy cow 7": "Cattle",
        "goatT252": "Goat",
        "Abo-6771_R1": "Missing",
        "bull": "Cattle",
        "Bos taurus x Bos indicus": "Cattle",
        "goatT203": "Goat",
        "sheep": "Sheep",
        "031": "Missing",
        "beef individual 5": "Cattle",
        "Camel1": "Camel",
        "caprine": "Goat",
        "bioreactor": "Missing",
        "goat 11": "Goat",
        "beef individual 3": "Cattle",
        "buffaloes": "Buffalo",
        "Rangifer tarandus 7S_N_A_M": "Deer",
        "Rangifer tarandus 11S_N_A_F": "Deer",
        "Rumen of Mediterranean buffaloes": "Buffalo",
        "LF160215": "Missing",
        "WQ yak": "Yak",
        "cattle_8": "Cattle",
        "Rangifer tarandus 8W_YN_A_M": "Deer",
        "goatT253": "Goat",
        "beef individual 12": "Cattle",
        "Bos taurus indicus": "Cattle",
        "Rangifer tarandus 27W_M_A_M": "Deer",
        "Abo-6764_R1": "Missing",
        '"Ovis aris" "Capra aegagrus hircus"': "Sheep/Goat",
        "dairy cows13": "Cattle",
        "dairy cows23": "Cattle",
        "bos_taurus": "Cattle",
        "Luing": "Cattle",
        "Camel-9": "Camel",
        "Sanhe heifers": "Cattle",
        "Dama dama": "Deer",
        "068": "Missing",
        "Camel-13": "Camel",
        "calf": "Cattle",
        "Goat-3": "Goat",
        "Bovine": "Cattle",
        "Goat-24": "Goat",
        "goat kids 10": "Goat",
        "Rangifer tarandus 10S_N_A_F": "Deer",
        "postlactating Holstein cows": "Cattle",
        "Camel-8": "Camel",
        "sheep-3": "Sheep",
        "bovine10 in CON": "Cattle",
        "bovine4 in CAR": "Cattle",
        "0162": "Missing",
        "Rangifer tarandus 19W_N_C": "Deer",
        "dairy cows6": "Cattle",
        "sheep-4": "Sheep",
        "Rangifer tarandus 14S_N_A_F": "Deer",
        "bovine5 in SCFP": "Cattle",
        "Goat-29": "Goat",
        "cattle_13": "Cattle",
        "Camel-36": "Camel",
        "Goat-15": "Goat",
        "Microorganism": "Missing",
        "camel-3": "Camel",
        "Yunling beef": "Cattle",
        "sheep-5": "Sheep",
        "Bos grunniens x Bos taurus": "Yak",
        "yak4": "Yak",
        "034": "Missing",
        "animal": "Missing",
        "Yak": "Yak",
        "rumencowA_replicate2": "Cattle",
        "bovine2 in CON": "Cattle",
        "0626": "Missing",
        "Dairy cow 16": "Cattle",
        "moose": "Moose",
        "goat 4": "Goat",
        "dairy cows18": "Cattle",
        "dairy cows22": "Cattle",
        "Sheep-4": "Sheep",
        "bovine9 in SCFP": "Cattle",
        "Elephas maximus indicus": "Elephant",
        "Angus bull": "Cattle",
        "0597": "Missing",
        "Camel-30": "Camel",
        "cattle_12": "Cattle",
        "goat 12": "Goat",
        "Charolais": "Cattle",
        "Cervus nippon": "Deer",
        "control": "Missing",
        "Simmental calf": "Cattle",
        "B. taurus": "Cattle",
        "goatC3": "Goat",
        "Rangifer tarandus 12W_YN_A_F": "Deer",
        "Rangifer tarandus 33W_M_A_F": "Deer",
        "beef individual 6": "Cattle",
        "Camel-32": "Camel",
        "cattle_10": "Cattle",
        "goat kids 8": "Goat",
        "LF150342": "Missing",
        "Goat-17": "Goat",
        "Jersey Heifer": "Cattle",
        "male bovine": "Cattle",
        "Cow/sheep": "Cattle/Sheep",
        "bovine6 in CAR": "Cattle",
        "Bos taurus coreanae": "Cattle",
        "rumencowA_replicate1": "Cattle",
        "Camel-33": "Camel",
        "Ovies aries": "Sheep",
        "Axis porcinus": "Deer",
        "Goat-4": "Goat",
        "Sheep": "Sheep",
        "Camel-16": "Camel",
        '"""Bovine, Dairy Cow"""': "Cattle",
        "Camel-3": "Camel",
        "Creole goat": "Goat",
        "beef individual 4": "Cattle",
        "Dairy cow 29": "Cattle",
        "Goat": "Goat",
        "Ovis aries": "Sheep",
        "Rangifer tarandus 2W_YN_C": "Deer",
        "Camel-10": "Camel",
        "Connochaetes taurinus": "Wildebeest",
        "Bos taurus Holstein-Friesian": "Cattle",
        "bovine5 in CON": "Cattle",
        "Camel-12": "Camel",
        "goatT352": "Goat",
        "beef individual 9": "Cattle",
        "Rangifer tarandus 32W_M_A": "Deer",
        "Holstein friesian cattle": "Cattle",
        '"Bos Taurus"': "Cattle",
        "Ovis canadensis": "Sheep",
        "cows": "Cattle",
        "0208": "Missing",
        "Sheep-18": "Sheep",
        "cattle_14": "Cattle",
        "bovine9 in CON": "Cattle",
        "Lamb": "Sheep",
        "Bos": "Cattle",
        "dairy cows10": "Cattle",
        "Capra hircus": "Goat",
        "Angus beef": "Cattle",
        "Montbeliarde Holstein Hybrid cattle": "Cattle",
        "goatC1": "Goat",
        "Dairy cow 27": "Cattle",
        "Camel-5": "Camel",
        "Rangifer tarandus 29W_M_A_F": "Deer",
        "Cow": "Cattle",
        "Lanzhou fat-tailed sheep": "Sheep",
        "Chinese Bohai Black beef cattle": "Cattle",
        "China:Zhu Madian": "Missing",
        "Dairy cow 17": "Cattle",
        "goat 3": "Goat",
        "Angus beef cattle": "Cattle",
        "holstein dairy cow": "Cattle",
        "goatT353": "Goat",
        "Nellore steers": "Cattle",
        "Rangifer tarandus 16S_N_C": "Deer",
        "Camel-2": "Camel",
        "dairy cows11": "Cattle",
        "cattle_18": "Cattle",
        "Sheep6": "Sheep",
        "Capra aegagrus hircus": "Goat",
        "Rangifer tarandus 4W_YN_Y": "Deer",
        "Holstein dairy cows": "Cattle",
        "dairy cows21": "Cattle",
        "goat kids 9": "Goat",
        "dairy cows7": "Cattle",
        "Camel-23": "Camel",
        "Not Applicable": "Missing",
        "bovine3 in CAR": "Cattle",
        "Dairy cow 21": "Cattle",
        "rumencowC_replicate3": "Cattle",
        "Calve": "Cattle",
        "sheep-10": "Sheep",
        "yak1": "Yak",
        "camel": "Camel",
        "Chinese Luxi Yellow beef cattle": "Cattle",
        "Abo-6765_R1": "Missing",
        "rumencowB_replicate1": "Cattle",
        "MISSING": "Missing",
        "Antoilocapra americana": "Antelope",
        "Rangifer tarandus 4S_YN_C": "Deer",
        "dairy calves": "Cattle",
        "Bos indicus": "Cattle",
        "Rangifer tarandus 14W_N_A_F": "Deer",
        "Capreolus pygargus": "Deer",
        "Rangifer tarandus 20W_N_A_M": "Deer",
        "Camel4": "Camel",
        "dairy cow-6": "Cattle",
        "goatH3": "Goat",
        "Rangifer tarandus 24W_M_C": "Deer",
        "ZB yak": "Yak",
        "SHEEP": "Sheep",
        "Odocoileus hemionus": "Deer",
        "Rupicapra rupicapra": "Chamois",
        "laboratory": "Missing",
        "Castor canadensis": "Beaver",
        "dairy cows2": "Cattle",
        "Rangifer tarandus 12S_N_A_F": "Deer",
        "Sheep2": "Sheep",
        "Rangifer tarandus 13S_N_C": "Deer",
        "Goat-36": "Goat",
        "holstein cow": "Cattle",
        "Camel-15": "Camel",
        "rumencowC_replicate2": "Cattle",
        "Tibetan goat 7": "Goat",
        "bovine2 in CAR": "Cattle",
        "Rangifer tarandus 25W_M_C": "Deer",
        "Cervus nippon yesoensis": "Deer",
        "bovine": "Cattle",
        "cattle_6": "Cattle",
        "Goat-9": "Goat",
        "goatH4": "Goat",
        "Rangifer tarandus 5S_YN_C": "Deer",
        "Mock_community": "Missing",
        "Camel-31": "Camel",
        "Procapra przewalskii": "Antelope",
        "goatH6": "Goat",
        "Dairy cow 15": "Cattle",
        "camel-2": "Camel",
        "Lama glama": "Llama",
        "HF151234": "Missing",
        "Ovirs aries": "Sheep",
        "Camel-26": "Camel",
        "Deer": "Deer",
        "cattle_17": "Cattle",
        "Simmental cattle": "Cattle",
        "Cervus elaphus": "Deer",
        "Sheep-6": "Sheep",
        "Rangifer tarandus 6S_YN_C": "Deer",
        "cattle_1": "Cattle",
        "Holstein": "Cattle",
        "Camel": "Camel",
        "dairy cow-8": "Cattle",
        "Bos taurus indicus (Nellore cattle)": "Cattle",
        "sheep-8": "Sheep",
        "rumencowC_replicate1": "Cattle",
        "esaries": "Sheep",
        "cattle_20": "Cattle",
        "Rangifer tarandus 15S_N_C": "Deer",
        "Rangifer tarandus 7W_YN_A_M": "Deer",
        "Dairy cow 10": "Cattle",
        "Not applicable": "Missing",
        "Camel-18": "Camel",
        "Camel-20": "Camel",
        "goat 8": "Goat",
        "camel3": "Camel",
        "cattle_3": "Cattle",
        "Beef cattle": "Cattle",
        "Camelus dromedarius": "Camel",
        "Dairy cow 18": "Cattle",
        "Camel-11": "Camel",
        "0": "Missing",
        "bos taurus": "Cattle",
        "Bison bison": "Bison",
        "Xiangxi yellow cattle": "Cattle",
        "HF150103": "Missing",
        "Goat-31": "Goat",
        "cattle_4": "Cattle",
        "0634": "Missing",
        "Camel5": "Camel",
        "dairy cow": "Cattle",
        "Ovies arie": "Sheep",
        "cow": "Cattle",
        "lamb": "Sheep",
        "camel-1": "Camel",
        "Cattle": "Cattle",
        "Goat-35": "Goat",
        "Sus scrofa": "Pig",
        "Oaries": "Sheep",
        "Sheep-3": "Sheep",
        "Dairy cattle": "Cattle",
        "SZ yak": "Yak",
        "Rangifer tarandus 9W_YN_A_M": "Deer",
        "Camel-7": "Camel",
        "goat kids 2": "Goat",
        "Lama guanicoe": "Guanaco",
        "Goat-14": "Goat",
        "lambs": "Sheep",
        "Ovies ares": "Sheep",
        "Camel-19": "Camel",
        "Rangifer tarandus 17W_N_C": "Deer",
        "beef individual 8": "Cattle",
        "Goat-21": "Goat",
        '"Bovine, Dairy Cow"': "Cattle",
        "Tibetan goat 1": "Goat",
        "Chinese Laoshan milk goat": "Goat",
        "LF150163": "Missing",
        "Sheep-11": "Sheep",
        "Goat-26": "Goat",
        "rumencowB_replicate3": "Cattle",
        "bovine1 in CON": "Cattle",
        "Dairy cow 20": "Cattle",
        "Cervus canadensis": "Deer",
        "hanwoo(Bos taurus coreanae), castrated": "Cattle",
        "Goat-18": "Goat",
        "Camel-24": "Camel",
        "Sheep5": "Sheep",
        "Ovies aies": "Sheep",
        "Sheep-13": "Sheep",
        "Camel-35": "Camel",
        "goatT201": "Goat",
        "Cryptotermes brevis": "Termite",
        "dairy cow-10": "Cattle",
        "Rangifer tarandus 9S_N_A_M": "Deer",
        "dairy cows12": "Cattle",
        "goatC2": "Goat",
        "Bos indicus x": "Cattle",
        "beef individual 2": "Cattle",
        "dairy cows5": "Cattle",
        "goat 10": "Goat",
        "Feed": "Missing",
        "Tibetan goat 8": "Goat",
        "Ovis": "Sheep",
        "bovine6 in SCFP": "Cattle",
        "Rangifer tarandus 16W_N_A_F": "Deer",
        "Abo-6793_R1": "Missing",
        "Goat-1": "Goat",
        "goat kids 3": "Goat",
        "sheep-9": "Sheep",
        "Zymo Mock #D6310": "Missing",
        "red deer sapiens": "Deer",
        "Dairy cow 14": "Cattle",
        "Sheep-14": "Sheep",
        "Tibetan goat 2": "Goat",
        "goat kids 18": "Goat",
        "goatH1": "Goat",
        "Camel-1": "Camel",
        "Rangifer tarandus 28W_M_A_F": "Deer",
        "Goat-23": "Goat",
        "Bos mutus": "Yak",
        "Rangifer tarandus 8S_N_A_M": "Deer",
        "Control": "Missing",
        "Guanzhong dairy goat": "Goat",
        "HF151027": "Missing",
        "Goat-32": "Goat",
        "Camel-17": "Camel",
        "bovine1 in SCFP": "Cattle",
        "goatC5": "Goat",
        "bovine3 in CON": "Cattle",
        "bovine7 in SCFP": "Cattle",
        "Missing": "Missing",
        "tibetan sheep": "Sheep",
        "Ovie aries": "Sheep",
        "Camel-29": "Camel",
        "Rangifer tarandus 23W_M_A_F": "Deer",
        "Karakul sheep": "Sheep",
        "Alcelaphus caama": "Hartebeest",
        "Goat-2": "Goat",
        "Goat-39": "Goat",
        "dairy cattle": "Cattle",
        "Vicugna pacos": "Alpaca",
        "Goat-37": "Goat",
        "0193": "Missing",
        "Dairy cow 24": "Cattle",
        "goatT301": "Goat",
        "Tibetan goat 3": "Goat",
        "goatC6": "Goat",
        "not collected": "Missing",
        "Dairy cow 26": "Cattle",
        "Abo-6780_R1": "Missing",
        "Camel-6": "Camel",
        "goat kids 12": "Goat",
        "Simmental crossbred cattle": "Cattle",
        "Capra ibex": "Goat",
        "Reagents": "Missing",
        "Sheep-12": "Sheep",
        "Buffalo": "Buffalo",
        "Sheep-1": "Sheep",
        "goatC4": "Goat",
        "dairy cows": "Cattle",
        "goat kids 13": "Goat",
        "bovine8 in SCFP": "Cattle",
        "Odocoileus virginianus": "Deer",
        "Huacaya alpaca": "Alpaca",
        "goat kids 16": "Goat",
        "Rangifer tarandus 13W_N_A_F": "Deer",
        "bovine2 in SCFP": "Cattle",
        "Holstein x Gyr": "Cattle",
        "Camel-25": "Camel",
        "YAK": "Yak",
        "capra hircus saanen crosses": "Goat",
        "cattle": "Cattle",
        "Rangifer tarandus 15W_N_A_F": "Deer",
        "Camel6": "Camel",
        "Dairy cow 11": "Cattle",
        "Bison": "Bison",
        "beef cattle": "Cattle",
        "Sheep-15": "Sheep",
        "COW": "Cattle",
        "Rangifer tarandus 1S_YN_A": "Deer",
        "camel2": "Camel",
        "Dairy Cow": "Cattle",
        "goat kids 4": "Goat",
        "Ov aries": "Sheep",
        "Aepyceros melampus": "Antelope",
        "Ovis aries musimon": "Sheep",
        "Rangifer tarandus 22W_N_A_M": "Deer",
        "goatT251": "Goat",
        "Dairy cow 2": "Cattle",
        "Oreamnos americanus": "Goat",
        "Dairy cow 12": "Cattle",
        "cattle_9": "Cattle",
        "yak6": "Yak",
        "goatT351": "Goat",
        "beef individual 7": "Cattle",
        "Goat-11": "Goat",
        "yak2": "Yak",
        "yaks": "Yak",
        "dairy cows14": "Cattle",
        "Sika deer": "Deer",
        "goat kids 5": "Goat",
        "Dairy cow 3": "Cattle",
        "goatH5": "Goat",
        "Bos taurus rumen": "Cattle",
        "microbes from fecal": "Missing",
        "Oviess": "Sheep",
        "Dairy cow 5": "Cattle",
        "dairy goats": "Goat",
        "Simmental": "Cattle",
        "Rusa unicolor": "Deer",
        "Bubalus bubalis": "Buffalo",
        "dairy cows1": "Cattle",
        "Goat-7": "Goat",
        "ewes": "Sheep",
        "Dairy cow 19": "Cattle",
        "Zymo Mock #D6307": "Missing",
        "missing": "Missing",
        "Goat-33": "Goat",
        "Deer (Capreolus pygargus)": "Deer",
        "Dairy cow 1": "Cattle",
        "yak3": "Yak",
        "Sheep-8": "Sheep",
        "Cervus albirostris": "Deer",
        "Holstein cows": "Cattle",
        "aries": "Sheep",
        "dairy cows20": "Cattle",
        "goatT202": "Goat",
        "Chordata": "Missing",
        "Giraffa camelopardalis": "Giraffe",
        "Bostaurus": "Cattle",
        "Oves aries": "Sheep",
        "Rangifer tarandus 18W_N_C": "Deer",
        "dairy cows16": "Cattle",
        "Rangifer tarandus 5W_YN_Y": "Deer",
        "0632": "Missing",
        "bovine5 in CAR": "Cattle",
        "Holstein bull": "Cattle",
        "Dairy cow 28": "Cattle",
        "goat kids 15": "Goat",
        "Hu Sheep": "Sheep",
        "Extraction_control_3": "Missing",
        "Goat-12": "Goat",
        "goat kids 14": "Goat",
        "Sheep-10": "Sheep",
        "Zymo Mock #D6308": "Missing",
        "sheep-1": "Sheep",
        "goat kids 6": "Goat",
        "Rucervus eldii": "Deer",
        "Ovi aries": "Sheep",
        "Calves": "Cattle",
        "Dairy cow 8": "Cattle",
        "Muntiacus reevesi": "Reeves's Muntjac",
        "Dairy cow 23": "Cattle",
        "bovine3 in SCFP": "Cattle",
        "beef individual 1": "Cattle",
        "dairy cows4": "Cattle",
        "Rangifer tarandus tarandus": "Deer",
        "Goat-6": "Goat",
        "Bos taurus": "Cattle",
        "sheep-6": "Sheep",
        "Notamacropus rufogriseus": "Wallaby",
        "Dairy cow 30": "Cattle",
        "Camel-4": "Camel",
        "Sheep3": "Sheep",
        "sika deer, elk and the hybrids": "Deer",
        "goat kids 1": "Goat",
        "Dairy cow 9": "Cattle",
        "goatT303": "Goat",
    }
    return (animal_mapping,)


@app.cell
def _(animal_mapping, r_data):
    r_data["host_general"] = [
        animal_mapping.get(h, "Missing") for h in r_data["host"]
    ]
    return


@app.cell
def _(r_data):
    # seperate the samples y sequencing strategy for further analysis
    amplicon_data = r_data.loc[r_data["LibraryStrategy"] == "AMPLICON"].copy()
    rnaseq_data = r_data.loc[r_data["LibraryStrategy"] == "RNA-Seq"].copy()
    wgs_data = r_data.loc[
        r_data["LibraryStrategy"].isin(["WGS", "OTHER"])
        & ~(
            r_data["DesignDescription"].isin(
                ["QPCR", "16sRNA-seq Short read", "16SrRNA"]
            )
        )
    ].copy()
    return (wgs_data,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## WGS Data

    Data specifically for the *in silico* proteomics.
    """)
    return


@app.cell
def _(wgs_data):
    wgs_data
    return


@app.cell
def _(wgs_data):
    print(f"Number of WGS studies: {len(wgs_data['SRAStudy'].unique())}")
    print(f"Number of samples: {len(wgs_data)}")
    print(f"Sequenincg technology: {wgs_data['Sequencer'].unique()}")
    return


@app.cell
def _(wgs_data):
    host_seq_counts = (
        wgs_data[["host", "host_general", "Sequencer", "sequencing_type"]]
        .value_counts()
        .reset_index()
        .rename(columns={"count": "Samples Sequenced"})
    )
    host_seq_counts
    return


@app.cell
def _(wgs_data):
    wgs_data["Sequencer"].value_counts()
    return


@app.cell
def _(wgs_data):
    wgs_data["host_general"].value_counts()
    return


@app.cell
def _(pd, wgs_data):
    pd.crosstab(wgs_data["Sequencer"], wgs_data["host"])
    return


@app.cell
def _(pd, wgs_data):
    pd.crosstab(wgs_data["Sequencer"], wgs_data["host_general"])
    return


@app.cell
def _(pd, wgs_data):
    pd.crosstab(wgs_data["sequencing_type"], wgs_data["host_general"])
    return


@app.cell
def _(px, wgs_data):
    data_with_missing = wgs_data.loc[wgs_data["host_general"] == "Missing"].copy()
    fig5 = px.histogram(
        data_frame=data_with_missing,
        x="Gb",
        marginal="violin",
        color="sequencing_type",
        template="plotly_white",
        nbins=100,
        title="SRA Metagenome: Missing host info Gb of data per sample on SRA",
        labels={"Gb": "Gb of sequencing data/sample", "count": "Count"},
        color_discrete_map={
            "long-read": px.colors.qualitative.Dark2[0],
            "short-read": px.colors.qualitative.Dark2[1],
        },
        category_orders={"sequencing_type": ["long-read", "short-read"]},
    )
    fig5.update_traces(
        marker=dict(line=dict(color="#000000", width=1)),
    )
    fig5.update_xaxes(tick0=0, nticks=20)
    fig5.update_yaxes(tick0=0, nticks=15)
    fig5.update_legends(title="Sequencing Type")
    fig5.show()
    return


@app.cell
def _(wgs_data):
    wgs_data.loc[wgs_data["host_general"] == "Missing"][
        ["SRAStudy", "Sequencer"]
    ].value_counts()
    return


@app.cell
def _(wgs_data):
    cattle_changes = {
        "SRP194489": "Cattle",
        "SRP632348": "Buffalo",
        "SRP194484": "Cattle",
        "SRP194481": "Cattle",
        "SRP194480": "Cattle",
        "SRP194490": "Cattle",
        "SRP194477": "Cattle",
        "SRP194479": "Cattle",
        "SRP194478": "Cattle",
        "SRP194487": "Cattle",
        "SRP194486": "Cattle",
        "ERP186382": "Cattle",
        "SRP665216": "Yak",
        "SRP576745": "Cattle",
        "ERP157061": "Cattle",
        "ERP149388": "Cattle",
        "ERP155812": "Cattle",
        "SRP068018": "Goat",
        "ERP023895": "Cattle",
        "ERP117106": "Cattle",
        "SRP234374": "Goats",
        "ERP127257": "Cattle",
        "SRP470037": "Yak",
        "SRP331775": "Cattle",
        "SRP447677": "Cattle",
        "ERP186382": "Cattle",
        "SRP270981": "Sheep",
        "ERP009980": "Cattle",
        "SRP422045": "Cattle",
        "SRP443269": "Cattle",
        "SRP250705": "Cattle",
        "ERP113798": "Cattle",
        "ERP155573": "Cattle",
        "SRP001061": "Cattle",
        "ERP188820": "Cattle",
        "SRP122512": "Cattle",
        "SRP122506": "Cattle",
        "SRP122511": "Cattle",
        "SRP120637": "Cattle",
        "SRP120636": "Cattle",
        "SRP120635": "Cattle",
        "SRP120638": "Cattle",
        "SRP120633": "Cattle",
        "ERP008817": "Antelope",
        "SRP004875": "Cattle",
        "SRP194476": "Cattle",
        "SRP194475": "Cattle",
        "SRP194473": "Cattle",
        "SRP194472": "Cattle",
        "SRP194469": "Cattle",
    }
    new_hosts = [
        cattle_changes.get(s, "Missing") if h == "Missing" else h
        for s, h in zip(wgs_data["SRAStudy"], wgs_data["host_general"])
    ]
    wgs_data["host_general"] = new_hosts
    return


@app.cell
def _(wgs_data):
    wgs_data.loc[wgs_data["SRAStudy"] == "SRP632348"]
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### All Rumen WGS Data
    """)
    return


@app.cell
def _(wgs_data):
    host_seq_counts2 = (
        wgs_data[["host", "host_general", "Sequencer", "sequencing_type"]]
        .value_counts()
        .reset_index()
        .rename(columns={"count": "Samples Sequenced"})
    )
    host_seq_counts2
    return (host_seq_counts2,)


@app.cell
def _(host_seq_counts2, px):
    fig = px.bar(
        data_frame=host_seq_counts2,
        x="host_general",
        y="Samples Sequenced",
        color="Sequencer",
        barmode="stack",
        template="plotly_white",
    )
    fig.show()
    return


@app.cell
def _():
    # fig2 = px.bar(
    #     data_frame=host_seq_counts2,
    #     x="host_general",
    #     y="Samples Sequenced",
    #     color="sequencing_type",
    #     barmode="stack",
    #     template="plotly_white",
    # )
    # fig2.show()
    return


@app.cell
def _(go, host_seq_counts2, px):
    cattle_long_short = (
        host_seq_counts2.loc[host_seq_counts2["host_general"] == "Cattle"]
        .groupby("sequencing_type")
        .sum("Samples Sequenced")
    )
    fig3 = go.Figure(
        data=[
            go.Pie(
                labels=cattle_long_short.index,
                values=cattle_long_short["Samples Sequenced"],
                hole=0.4,
                pull=[0, 0.1],
                marker=dict(colors=px.colors.qualitative.Dark2),
            )
        ]
    )
    fig3.update_traces(
        textposition="inside",
        textinfo="percent+label+value",
        marker=dict(line=dict(color="#000000", width=1)),
    )
    fig3.update_layout(
        title_text="Sequencing Type for Cattle WGS Samples on SRA", width=600
    )
    fig3.show()
    return


@app.cell
def _(px, wgs_data):
    fig4 = px.histogram(
        data_frame=wgs_data.loc[wgs_data["host_general"] == "Cattle"],
        x="Gb",
        marginal="violin",
        color="sequencing_type",
        template="plotly_white",
        nbins=200,
        title="SRA Cattle Metagenome: Gb of data per sample on SRA",
        labels={"Gb": "Gb of sequencing data/sample", "count": "Count"},
        color_discrete_map={
            "long-read": px.colors.qualitative.Dark2[0],
            "short-read": px.colors.qualitative.Dark2[1],
        },
    )
    fig4.update_traces(
        marker=dict(line=dict(color="#000000", width=1)),
    )
    fig4.update_xaxes(tick0=0, nticks=20)
    fig4.update_yaxes(tick0=0, nticks=15)
    fig4.update_legends(title="Sequencing Type")
    fig4.show()
    return


@app.cell
def _(wgs_data):
    wgs_data.loc[wgs_data["sequencing_type"] == "long-read"]
    return


@app.cell
def _(px, wgs_data):
    fig6 = px.histogram(
        data_frame=wgs_data.loc[
            (wgs_data["host_general"] == "Cattle")
            & (wgs_data["sequencing_type"] == "long-read")
        ],
        x="Gb",
        marginal="violin",
        color="Sequencer",
        template="plotly_white",
        nbins=200,
        title="SRA Cattle Metagenome: Gb of data per sample on SRA",
        labels={"Gb": "Gb of sequencing data/sample", "count": "Count"},
        color_discrete_map={
            "long-read": px.colors.qualitative.Dark2[0],
            "short-read": px.colors.qualitative.Dark2[1],
        },
    )
    fig6.update_traces(
        marker=dict(line=dict(color="#000000", width=1)),
    )
    fig6.update_xaxes(tick0=0, nticks=20)
    fig6.update_yaxes(tick0=0, nticks=15)
    fig6.update_legends(title="Sequencing Type")
    fig6.show()
    return


@app.cell
def _(px, wgs_data):
    fig7 = px.histogram(
        data_frame=wgs_data.loc[
            (wgs_data["host_general"] == "Cattle")
            & (wgs_data["Published"] >= "2015")
        ],
        x="Gb",
        marginal="violin",
        color="sequencing_type",
        template="plotly_white",
        nbins=200,
        title="SRA Cattle Metagenome: Gb of data per sample on SRA",
        labels={"Gb": "Gb of sequencing data/sample", "count": "Count"},
        color_discrete_map={
            "long-read": px.colors.qualitative.Dark2[0],
            "short-read": px.colors.qualitative.Dark2[1],
        },
    )
    fig7.update_traces(
        marker=dict(line=dict(color="#000000", width=1)),
    )
    fig7.update_xaxes(tick0=0, nticks=20)
    fig7.update_yaxes(tick0=0, nticks=15)
    fig7.update_legends(title="Sequencing Type")
    fig7.show()
    return


@app.cell
def _(px, wgs_data):
    fig8 = px.scatter(
        data_frame=wgs_data.loc[wgs_data["host_general"] == "Cattle"],
        x="Published",
        y="Gb",
        color="sequencing_type",
        trendline="ols",
        template="plotly_white",
        hover_data=["SRAStudy", "Sequencer"],
    )
    fig8.update_traces(marker=dict(line=dict(color="#000000", width=1)))
    fig8.show()
    return


@app.cell
def _(px, wgs_data):
    cattle_wgs = wgs_data.loc[wgs_data["host_general"] == "Cattle"]
    fig9 = px.histogram(
        data_frame=cattle_wgs,
        x=cattle_wgs["Published"].dt.year,
        nbins=26,
        template="plotly_white",
        title="Number of Cattle Metagenome WGS samples per year on SRA/ENA",
        labels={"x": "Year", "count": "Number of WGS samples"},
    )
    fig9.update_traces(marker=dict(line=dict(color="#000000", width=1)))
    fig9.update_xaxes(tick0=0, nticks=20, tickangle=315)
    fig9.show()
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Data Selection

    - Remove outdated inaccurate technology
    - Use data from >=2018 (max 8 years old)
    - Use data >= 5Gb sequencing data
    - Use only Cattle data
    """)
    return


@app.cell
def _(np, wgs_data):
    # wgs_data["Sequencer"].unique()

    seq_blacklist = [
        "454 GS FLX+",
        np.nan,
        "Ion Torrent PGM",
        "454 GS FLX Titanium",
        "454 GS FLX",
    ]
    selected_wgs_data = wgs_data.loc[
        ~(wgs_data["Sequencer"].isin(seq_blacklist))
        & (wgs_data["Published"] >= "2018")
        & (wgs_data["Gb"] >= 4)
        & (wgs_data["host_general"] == "Cattle")
    ]
    selected_wgs_data.shape
    return (selected_wgs_data,)


@app.cell
def _(selected_wgs_data):
    host_seq_counts3 = (
        selected_wgs_data[["host", "host_general", "Sequencer", "sequencing_type"]]
        .value_counts()
        .reset_index()
        .rename(columns={"count": "Samples Sequenced"})
    )
    host_seq_counts3
    return (host_seq_counts3,)


@app.cell
def _(go, host_seq_counts3, px):
    cattle_long_short2 = host_seq_counts3.groupby("sequencing_type").sum(
        "Samples Sequenced"
    )
    fig10 = go.Figure(
        data=[
            go.Pie(
                labels=cattle_long_short2.index,
                values=cattle_long_short2["Samples Sequenced"],
                hole=0.2,
                pull=[0, 0.1],
                marker=dict(colors=px.colors.qualitative.Dark2),
            )
        ]
    )
    fig10.update_traces(
        textposition="inside",
        textinfo="percent+label+value",
        marker=dict(line=dict(color="#000000", width=1)),
    )
    fig10.update_layout(
        title_text="Sequencing Type for Selected Cattle WGS Samples on SRA", width=600
    )
    fig10.show()
    return (cattle_long_short2,)


@app.cell
def _(cattle_long_short2):
    cattle_long_short2
    return


@app.cell
def _(px, selected_wgs_data):
    fig11 = px.histogram(
        data_frame=selected_wgs_data,
        x="Gb",
        marginal="violin",
        color="sequencing_type",
        template="plotly_white",
        nbins=200,
        title="SRA Cattle Metagenome: Gb of data per sample on SRA",
        labels={"Gb": "Gb of sequencing data/sample", "count": "Count"},
        color_discrete_map={
            "long-read": px.colors.qualitative.Dark2[0],
            "short-read": px.colors.qualitative.Dark2[1],
        },
    )
    fig11.update_traces(
        marker=dict(line=dict(color="#000000", width=1)),
    )
    fig11.update_xaxes(tick0=0, nticks=20)
    fig11.update_yaxes(tick0=0, nticks=15)
    fig11.update_legends(title="Sequencing Type")
    fig11.show()
    return


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
